Custom links plugin
flotiq/flotiq-docs pull request #154
Opened 2023-06-02 14:26 UTC by Hello-Flotiq

2023-06-02 22:40 UTC, andrzejwp requested changes

2023-06-02 22:40 UTC, andrzejwp commented on mkdocs.yml
> +      - 'Custom Links': panel/Plugins/Custom-links.md
This was missing in the original version of the MR. Without this - the page will not appear in the main nav or the sitemaps.

2023-06-02 22:40 UTC, andrzejwp commented on docs/panel/Plugins/Custom-links.md
> +## Examples
Adding Examples section to better demonstrate how this plugin can be used

2023-06-02 22:40 UTC, andrzejwp commented on docs/panel/Plugins/Custom-links.md
> +![Netlify build button in Flotiq editor](images/plugins-custom-links-3.png){: .center .width50 .border}
Please fix the caption of this image. It's not related to netlify.

2023-06-02 22:40 UTC, andrzejwp commented on docs/panel/Plugins/Custom-links.md
> +![Setting up Netlify Build in Flotiq](images/plugins-custom-links-2.png){: .center .width50 .border}
Please fix the caption of this image. It's not related to netlify.

2023-06-02 22:41 UTC, andrzejwp commented
It would be nice to see a short description of changes included in this MR as well.

2023-06-02 22:42 UTC, andrzejwp commented
This PR refers to #154

2023-06-05 13:54 UTC, trzcina commented
I've checked the change requests and updates; merging

2023-06-05 13:54 UTC, merged